platform :ios, '9.3'
use_frameworks!

target 'ANPlayerController_Example' do
  pod 'ANPlayerController', :path => '../'
  pod 'SnapKit', '>= 3.0.0'
  pod 'SDWebImage'

  target 'ANPlayerController_Tests' do
    inherit! :search_paths

    
  end
end
